# Site settings
title: KayMic
tagline: IT &amp; Web Development
description: > # ignore newlines
  Experienced Web Developer with extensive knowledge in Internet Services, Information Technology, and Digital Multimedia.
email: kevin@kaymic.com

baseurl: ""
url: "http://kaymic.com"
paginate: 10
paginate_path: "portfolio/:num"

# Build settings
markdown: kramdown
permalink: pretty
